ALTER TABLE GAME_VARIANT ADD SUPERSEDED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE GAME_VARIANT ADD SUPERSEDED_BY_VARIANT_ID BIGINT;
ALTER TABLE VARIANT_RETIREMENT_DECISION ADD SUPERSEDED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE VARIANT_RETIREMENT_DECISION ADD SUPERSEDED_BY_VARIANT_ID BIGINT;
