-- Flyway Migration: V2.4.3.5
-- Purpose: Store provenance-bearing timestamp evidence without conflating import time with release time.

CREATE SEQUENCE VARIANT_TIMESTAMP_EVIDENCE_SEQ INCREMENT BY 50;

CREATE TABLE VARIANT_TIMESTAMP_EVIDENCE
(
    ID          BIGINT                   NOT NULL PRIMARY KEY,
    VARIANT_ID  BIGINT                   NOT NULL,
    KIND        CHARACTER VARYING(255)  NOT NULL,
    OBSERVED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PROVENANCE  CHARACTER LARGE OBJECT   NOT NULL,
    RECORDED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    ACTOR       CHARACTER VARYING(255)  NOT NULL,
    CONSTRAINT FK_VARIANT_TIMESTAMP_EVIDENCE_VARIANT
        FOREIGN KEY (VARIANT_ID) REFERENCES GAME_VARIANT
            ON DELETE CASCADE
);
