ALTER TABLE GAME_VARIANT ADD QUARANTINE_PATH CHARACTER VARYING(255);
CREATE SEQUENCE VARIANT_QUARANTINE_RECORD_SEQ INCREMENT BY 50;
CREATE TABLE VARIANT_QUARANTINE_RECORD (
    ID BIGINT NOT NULL PRIMARY KEY,
    VARIANT_ID BIGINT NOT NULL,
    ORIGINAL_PATH CHARACTER VARYING(255) NOT NULL,
    QUARANTINE_PATH CHARACTER VARYING(255) NOT NULL,
    QUARANTINED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    RECOVERABLE_UNTIL TIMESTAMP WITH TIME ZONE NOT NULL,
    ACTOR CHARACTER VARYING(255) NOT NULL,
    REASON CHARACTER VARYING(255) NOT NULL,
    RESTORED_AT TIMESTAMP WITH TIME ZONE,
    RESTORED_BY CHARACTER VARYING(255),
    CONSTRAINT FK_VARIANT_QUARANTINE_VARIANT FOREIGN KEY (VARIANT_ID) REFERENCES GAME_VARIANT
);
