-- Flyway Migration: V2.4.3.6
-- Purpose: Persist administrator review records without applying a classification or modifying a source path.

CREATE SEQUENCE VARIANT_CLASSIFICATION_REVIEW_SEQ INCREMENT BY 50;
CREATE SEQUENCE VARIANT_CLASSIFICATION_REVIEW_DECISION_SEQ INCREMENT BY 50;

CREATE TABLE VARIANT_CLASSIFICATION_REVIEW
(
    ID BIGINT NOT NULL PRIMARY KEY, SOURCE_GAME_ID BIGINT NOT NULL, SOURCE_VARIANT_ID BIGINT NOT NULL, TARGET_GAME_ID BIGINT NOT NULL,
    CONFIDENCE INTEGER NOT NULL, EXPLANATION CHARACTER LARGE OBJECT NOT NULL, EVIDENCE CHARACTER LARGE OBJECT NOT NULL,
    STATE CHARACTER VARYING(255) NOT NULL, CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL, CREATED_BY CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT FK_CLASSIFICATION_REVIEW_SOURCE_GAME FOREIGN KEY (SOURCE_GAME_ID) REFERENCES GAME ON DELETE CASCADE,
    CONSTRAINT FK_CLASSIFICATION_REVIEW_SOURCE_VARIANT FOREIGN KEY (SOURCE_VARIANT_ID) REFERENCES GAME_VARIANT ON DELETE CASCADE,
    CONSTRAINT FK_CLASSIFICATION_REVIEW_TARGET_GAME FOREIGN KEY (TARGET_GAME_ID) REFERENCES GAME ON DELETE CASCADE
);

CREATE TABLE VARIANT_CLASSIFICATION_REVIEW_DECISION
(
    ID BIGINT NOT NULL PRIMARY KEY, REVIEW_ID BIGINT NOT NULL, PREVIOUS_STATE CHARACTER VARYING(255) NOT NULL,
    NEW_STATE CHARACTER VARYING(255) NOT NULL, DECIDED_AT TIMESTAMP WITH TIME ZONE NOT NULL, ACTOR CHARACTER VARYING(255) NOT NULL,
    REASON CHARACTER LARGE OBJECT,
    CONSTRAINT FK_CLASSIFICATION_REVIEW_DECISION_REVIEW FOREIGN KEY (REVIEW_ID) REFERENCES VARIANT_CLASSIFICATION_REVIEW ON DELETE CASCADE
);
