-- Flyway Migration: V2.4.0.6
-- Purpose: Allow one variant content item to represent multiple source paths.

CREATE TABLE VARIANT_CONTENT_PATHS
(
    VARIANT_CONTENT_ID BIGINT                  NOT NULL,
    PATH_INDEX         INTEGER                 NOT NULL,
    PATH               CHARACTER VARYING(4096) NOT NULL,
    CONSTRAINT PK_VARIANT_CONTENT_PATHS
        PRIMARY KEY (VARIANT_CONTENT_ID, PATH_INDEX),
    CONSTRAINT FK_VARIANT_CONTENT_PATHS_CONTENT
        FOREIGN KEY (VARIANT_CONTENT_ID) REFERENCES VARIANT_CONTENT
);

INSERT INTO VARIANT_CONTENT_PATHS
    (VARIANT_CONTENT_ID, PATH_INDEX, PATH)
SELECT ID, 0, PATH
FROM VARIANT_CONTENT
WHERE PATH IS NOT NULL;
