-- Flyway Migration: V2.4.3.4
-- Purpose: Keep administrator-verified local and public Steam update markers separate from folder labels.

ALTER TABLE GAME_VARIANT ADD LOCAL_BUILD_VERSION CHARACTER VARYING(512);
ALTER TABLE GAME_VARIANT ADD LOCAL_BUILD_OBSERVED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE GAME_VARIANT ADD STEAM_UPDATE_MARKER CHARACTER VARYING(512);
ALTER TABLE GAME_VARIANT ADD STEAM_METADATA_OBSERVED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE GAME_VARIANT ADD STEAM_METADATA_SOURCE CHARACTER LARGE OBJECT;
ALTER TABLE GAME_VARIANT ADD STEAM_METADATA_CHECKED_AT TIMESTAMP WITH TIME ZONE;
