-- Flyway Migration: V2.4.0.3
-- Purpose: Add game variants and selectable variant content.

CREATE SEQUENCE GAME_VARIANT_SEQ
    INCREMENT BY 50;

CREATE SEQUENCE VARIANT_CONTENT_SEQ
    INCREMENT BY 50;

CREATE TABLE GAME_VARIANT
(
    ID                    BIGINT                 NOT NULL
        PRIMARY KEY,
    FILE_SIZE             BIGINT,
    IS_DEFAULT            BOOLEAN                NOT NULL,
    IS_LATEST_FOR_VARIANT BOOLEAN                NOT NULL,
    LAUNCH_ARGS           CHARACTER LARGE OBJECT,
    LINK_FALLBACK_REASON  CHARACTER LARGE OBJECT,
    LINK_STATUS           CHARACTER VARYING(255),
    NAME                  CHARACTER VARYING(255) NOT NULL,
    PATCH_INFO            CHARACTER LARGE OBJECT,
    PATH                  CHARACTER VARYING(255) NOT NULL
        CONSTRAINT UK_GAME_VARIANT_PATH
            UNIQUE,
    STEAM_APP_ID          CHARACTER VARYING(255),
    VERSION               CHARACTER VARYING(255) NOT NULL,
    GAME_ID               BIGINT,
    CONSTRAINT FK_GAME_VARIANT_GAME
        FOREIGN KEY (GAME_ID) REFERENCES GAME
);

CREATE TABLE VARIANT_CONTENT
(
    ID               BIGINT                 NOT NULL
        PRIMARY KEY,
    DEFAULT_SELECTED BOOLEAN                NOT NULL,
    FILE_SIZE        BIGINT,
    NAME             CHARACTER VARYING(255) NOT NULL,
    PATH             CHARACTER VARYING(255) NOT NULL,
    REQUIRED         BOOLEAN                NOT NULL,
    TYPE             CHARACTER VARYING(255),
    VARIANT_ID       BIGINT,
    CONSTRAINT FK_VARIANT_CONTENT_VARIANT
        FOREIGN KEY (VARIANT_ID) REFERENCES GAME_VARIANT
);

CREATE TABLE GAME_VARIANT_TAGS
(
    GAME_VARIANT_ID BIGINT NOT NULL,
    TAGS            CHARACTER VARYING(255),
    CONSTRAINT FK_GAME_VARIANT_TAGS_VARIANT
        FOREIGN KEY (GAME_VARIANT_ID) REFERENCES GAME_VARIANT
);

CREATE TABLE VARIANT_CONTENT_TAGS
(
    VARIANT_CONTENT_ID BIGINT NOT NULL,
    TAGS               CHARACTER VARYING(255),
    CONSTRAINT FK_VARIANT_CONTENT_TAGS_CONTENT
        FOREIGN KEY (VARIANT_CONTENT_ID) REFERENCES VARIANT_CONTENT
);

INSERT INTO GAME_VARIANT
    (ID, FILE_SIZE, IS_DEFAULT, IS_LATEST_FOR_VARIANT, LINK_STATUS, NAME, PATH, VERSION, GAME_ID)
SELECT NEXT VALUE FOR GAME_VARIANT_SEQ,
       FILE_SIZE,
       TRUE,
       TRUE,
       'DIRECT',
       'Normal',
       PATH,
       '0',
       ID
FROM GAME
WHERE PATH IS NOT NULL;

INSERT INTO VARIANT_CONTENT
    (ID, DEFAULT_SELECTED, FILE_SIZE, NAME, PATH, REQUIRED, TYPE, VARIANT_ID)
SELECT NEXT VALUE FOR VARIANT_CONTENT_SEQ,
       TRUE,
       FILE_SIZE,
       'Base game',
       PATH,
       TRUE,
       'BASE',
       ID
FROM GAME_VARIANT;
