-- Additive host-owned creation journal; no active seeding capability is enabled.
CREATE TABLE TORRENT_SEED_INTENT (
    ID UUID NOT NULL PRIMARY KEY,
    CLIENT_ID UUID NOT NULL,
    SNAPSHOT_ID UUID NOT NULL,
    MANIFEST_DIGEST CHARACTER VARYING(64) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    STATE CHARACTER VARYING(255) NOT NULL,
    OPERATION_TOKEN UUID,
    METADATA_TASK_ID CHARACTER VARYING(128),
    METADATA_DIGEST CHARACTER VARYING(64),
    METADATA_BYTES BIGINT,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    VERSION BIGINT NOT NULL,
    CONSTRAINT UK_TORRENT_SEED_SNAPSHOT UNIQUE (CLIENT_ID, SNAPSHOT_ID),
    -- CASE remains evaluable after the Flyway connection closes in the H2 regression test.
    CONSTRAINT CK_TORRENT_SEED_STATE CHECK (CASE STATE
        WHEN 'DRAFT' THEN TRUE WHEN 'CREATION_IN_FLIGHT' THEN TRUE
        WHEN 'CREATION_UNCERTAIN' THEN TRUE WHEN 'METADATA_PENDING_VALIDATION' THEN TRUE
        WHEN 'REFUSED' THEN TRUE ELSE FALSE END),
    CONSTRAINT CK_TORRENT_SEED_TOKEN CHECK (CASE STATE
        WHEN 'DRAFT' THEN OPERATION_TOKEN IS NULL
        WHEN 'REFUSED' THEN OPERATION_TOKEN IS NULL
        ELSE OPERATION_TOKEN IS NOT NULL END),
    CONSTRAINT CK_TORRENT_SEED_METADATA CHECK (
        (STATE = 'METADATA_PENDING_VALIDATION' AND METADATA_TASK_ID IS NOT NULL AND METADATA_DIGEST IS NOT NULL AND METADATA_BYTES BETWEEN 1 AND 1048576)
        OR (STATE <> 'METADATA_PENDING_VALIDATION' AND METADATA_TASK_ID IS NULL AND METADATA_DIGEST IS NULL AND METADATA_BYTES IS NULL)
    )
);
CREATE INDEX IX_TORRENT_SEED_STATE_UPDATED ON TORRENT_SEED_INTENT (STATE, UPDATED_AT);
