-- Reserved after scan checkpoint migrations 35/36; never rename an applied migration.
CREATE SEQUENCE ACQUISITION_TRANSFER_SEQ INCREMENT BY 50;
CREATE SEQUENCE ACQUISITION_TRANSFER_AUDIT_SEQ INCREMENT BY 50;
CREATE TABLE ACQUISITION_TRANSFER (
 ID BIGINT NOT NULL PRIMARY KEY, CANDIDATE_ID BIGINT NOT NULL UNIQUE,
 INDEXER_ID CHARACTER VARYING(255) NOT NULL, TORRENT_HASH CHARACTER VARYING(255) NOT NULL UNIQUE,
 MAGNET CHARACTER VARYING(8192) NOT NULL, STATE CHARACTER VARYING(255) NOT NULL, VERSION BIGINT NOT NULL,
 UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL, OPERATION_TOKEN CHARACTER VARYING(36),
 CONSTRAINT FK_ACQUISITION_CANDIDATE FOREIGN KEY (CANDIDATE_ID) REFERENCES GAME_REQUEST_CANDIDATE
);
CREATE TABLE ACQUISITION_TRANSFER_AUDIT (
 ID BIGINT NOT NULL PRIMARY KEY, TRANSFER_ID BIGINT NOT NULL,
 OPERATION CHARACTER VARYING(255) NOT NULL, ACTOR CHARACTER VARYING(255) NOT NULL,
 REASON CHARACTER VARYING(4096) NOT NULL, RECORDED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
 CONSTRAINT FK_ACQUISITION_AUDIT_TRANSFER FOREIGN KEY (TRANSFER_ID) REFERENCES ACQUISITION_TRANSFER
);
