-- Flyway Migration: V2.4.3.2
-- Purpose: Preserve an administrator-visible audit trail for game-request status decisions.

CREATE SEQUENCE GAME_REQUEST_STATUS_CHANGE_SEQ INCREMENT BY 50;

CREATE TABLE GAME_REQUEST_STATUS_CHANGE
(
    ID                  BIGINT                  NOT NULL PRIMARY KEY,
    GAME_REQUEST_ID     BIGINT                  NOT NULL,
    PREVIOUS_STATUS     CHARACTER VARYING(255) NOT NULL,
    NEW_STATUS          CHARACTER VARYING(255) NOT NULL,
    CHANGED_AT          TIMESTAMP WITH TIME ZONE NOT NULL,
    ACTOR               CHARACTER VARYING(255) NOT NULL,
    REASON              CHARACTER LARGE OBJECT,
    CONSTRAINT FK_GAME_REQUEST_STATUS_CHANGE_REQUEST
        FOREIGN KEY (GAME_REQUEST_ID) REFERENCES GAME_REQUEST
            ON DELETE CASCADE
);
