-- Flyway Migration: V2.4.3.7
-- Purpose: Store advisory retention-policy metadata and its audit trail; no content action is introduced.

CREATE SEQUENCE LIBRARY_RETENTION_POLICY_SEQ INCREMENT BY 50;
CREATE SEQUENCE LIBRARY_RETENTION_POLICY_CHANGE_SEQ INCREMENT BY 50;

CREATE TABLE LIBRARY_RETENTION_POLICY
(
    ID BIGINT NOT NULL PRIMARY KEY, LIBRARY_ID BIGINT NOT NULL UNIQUE,
    MODE CHARACTER VARYING(255) NOT NULL, KEEP_LATEST_COUNT INTEGER, GRACE_PERIOD_DAYS INTEGER,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL, UPDATED_BY CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT FK_LIBRARY_RETENTION_POLICY_LIBRARY FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY ON DELETE CASCADE
);

CREATE TABLE LIBRARY_RETENTION_POLICY_CHANGE
(
    ID BIGINT NOT NULL PRIMARY KEY, POLICY_ID BIGINT NOT NULL,
    PREVIOUS_MODE CHARACTER VARYING(255) NOT NULL, PREVIOUS_KEEP_LATEST_COUNT INTEGER, PREVIOUS_GRACE_PERIOD_DAYS INTEGER,
    NEW_MODE CHARACTER VARYING(255) NOT NULL, NEW_KEEP_LATEST_COUNT INTEGER, NEW_GRACE_PERIOD_DAYS INTEGER,
    CHANGED_AT TIMESTAMP WITH TIME ZONE NOT NULL, ACTOR CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT FK_LIBRARY_RETENTION_POLICY_CHANGE_POLICY FOREIGN KEY (POLICY_ID) REFERENCES LIBRARY_RETENTION_POLICY ON DELETE CASCADE
);
