-- Flyway Migration: V2.4.3.3
-- Purpose: Record reversible in-application retirement decisions without changing any path or file.

ALTER TABLE GAME_VARIANT ADD RETIREMENT_STATE CHARACTER VARYING(255) DEFAULT 'ACTIVE' NOT NULL;
ALTER TABLE GAME_VARIANT ADD RETIREMENT_REVIEW_AT TIMESTAMP WITH TIME ZONE;

CREATE SEQUENCE VARIANT_RETIREMENT_DECISION_SEQ INCREMENT BY 50;

CREATE TABLE VARIANT_RETIREMENT_DECISION
(
    ID             BIGINT                   NOT NULL PRIMARY KEY,
    VARIANT_ID     BIGINT                   NOT NULL,
    PREVIOUS_STATE CHARACTER VARYING(255)  NOT NULL,
    NEW_STATE      CHARACTER VARYING(255)  NOT NULL,
    DECIDED_AT     TIMESTAMP WITH TIME ZONE NOT NULL,
    ACTOR          CHARACTER VARYING(255)  NOT NULL,
    REASON         CHARACTER LARGE OBJECT,
    REVIEW_AT      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_VARIANT_RETIREMENT_DECISION_VARIANT
        FOREIGN KEY (VARIANT_ID) REFERENCES GAME_VARIANT
            ON DELETE CASCADE
);
