"""Linux CI/staging only: disposable actual-image scan, never production mounts.

Requires an already available immutable image, matching H2 JAR path within it,
and explicitly supplied metadata plugin JAR. No images are pulled or published.
Only synthetic inputs generated by seed-scan-fixture.py are mounted.
"""
import argparse
import base64
import hashlib
import http.cookiejar
import importlib.util
import json
import io
import os
from pathlib import Path
import re
import secrets
import shlex
import subprocess
import tempfile
import time
import urllib.parse
import urllib.request
import zipfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--image", required=True)
    parser.add_argument("--source-revision", required=True)
    parser.add_argument("--h2-jar", required=True, help="Absolute path within the selected image")
    parser.add_argument("--metadata-plugin", required=True, type=Path)
    parser.add_argument("--direct-plugin", required=True, type=Path)
    parser.add_argument("--metadata-plugin-id", default="org.gameyfin.plugins.metadata.steam")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--runtime-uid", default="1337")
    parser.add_argument("--runtime-gid", default="1337")
    parser.add_argument("--docker-prefix", default="", help="Optional CLI prefix, for example sudo -n")
    parser.add_argument("--interrupt-scan", action="store_true", help="Kill only this disposable fixture while an active scan is observed, then restart and recover")
    parser.add_argument("--external-probe", type=Path, help="Optional reviewed staging-only Python probe receiving synthetic fixture context on stdin and credentials only in child environment")
    parser.add_argument("--proxy-image", help="Immutable cached proxy image supplied to an external probe")
    args = parser.parse_args()
    if not re.fullmatch(r"(?:[^\s]+@)?sha256:[a-f0-9]{64}", args.image):
        raise ValueError("Require immutable digest or local image ID")
    if args.source_revision != "baseline-unknown" and (
            not re.fullmatch(r"[a-f0-9]{40}", args.source_revision) or set(args.source_revision) == {"0"}):
        raise ValueError("Require exact reviewed source revision or explicit baseline-unknown")
    if args.output.exists() or not args.metadata_plugin.is_file() or not args.direct_plugin.is_file():
        raise ValueError("Require new output and explicit plugin JARs")
    if not args.h2_jar.startswith("/") or not args.runtime_uid.isdecimal() or not args.runtime_gid.isdecimal():
        raise ValueError("Invalid image runtime configuration")
    # No user-selected data directory: all mount sources originate in this new private leaf.
    root = Path(tempfile.mkdtemp(prefix="gameyfin-synthetic-scan-"))
    token = secrets.token_hex(8)
    name, network = "gameyfin-scan-" + token, "gameyfin-scan-net-" + token
    docker_command = shlex.split(args.docker_prefix) + ["docker"]
    def docker(*command):
        return subprocess.check_output([*docker_command, *command], text=True).strip()
    def request(path, body=None):
        headers = {"Content-Type": "application/json", "X-CSRF-Token": csrf} if body is not None else {}
        value = opener.open(urllib.request.Request(base + path,
            json.dumps(body).encode() if body is not None else None, headers), timeout=30).read()
        return value
    def snapshot():
        with telemetry.open(metrics, timeout=10) as response:
            return response.read(2 * 1024 * 1024).decode()
    def metric(name, selector=None, text=None):
        if text is None: text = snapshot()
        return sum(float(line.rsplit(" ", 1)[1]) for line in text.splitlines()
            if (line.startswith(name + "{") or line.startswith(name + " "))
            and (selector is None or selector in line))
    report = {"scope": "synthetic actual-image scan; not production acceptance",
        "image": args.image, "sourceRevision": args.source_revision,
        "sourceProvenanceKnown": args.source_revision != "baseline-unknown",
        "heapLimit": "512m", "containerLimit": "1536m", "scanResults": []}
    try:
        spec = importlib.util.spec_from_file_location("seed", Path(__file__).with_name("seed-scan-fixture.py"))
        seed = importlib.util.module_from_spec(spec); spec.loader.exec_module(seed)
        seed.generate(root / "fixture", "/fixture")
        manifest = json.loads((root / "fixture" / "manifest.json").read_text())
        expected_games = {game["gameId"]: game for game in manifest["games"]}
        for directory in ("db", "data", "logs", "plugins", "plugindata"):
            (root / directory).mkdir(mode=0o777)
            os.chmod(root / directory, 0o777)
        import shutil
        shutil.copyfile(args.metadata_plugin, root / "plugins" / args.metadata_plugin.name)
        shutil.copyfile(args.direct_plugin, root / "plugins" / args.direct_plugin.name)
        env = root / "runtime.env"
        env.write_text("APP_KEY=" + base64.b64encode(os.urandom(32)).decode() +
            "\nAPP_URL=http://localhost:8080\nJAVA_OPTS_OVERRIDE=-Xms128m -Xmx512m -XX:MaxMetaspaceSize=256m -XX:+ExitOnOutOfMemoryError\n")
        env.chmod(0o600)
        image = json.loads(docker("image", "inspect", args.image))[0]
        labels = image["Config"].get("Labels") or {}
        revision = labels.get("org.opencontainers.image.revision")
        if args.source_revision != "baseline-unknown" and revision != args.source_revision:
            raise RuntimeError("Selected image revision differs from supplied reviewed head")
        report["resolvedImageId"] = image["Id"]
        report["imageVersion"] = labels.get("org.opencontainers.image.version")
        report["pluginHashes"] = {plugin.name: hashlib.sha256(plugin.read_bytes()).hexdigest()
            for plugin in (args.metadata_plugin, args.direct_plugin)}
        docker("network", "create", "--internal", network)
        mounts = []
        for directory in ("db", "data", "logs", "plugins", "plugindata"):
            mounts += ["--mount", f"type=bind,src={root / directory},dst=/opt/gameyfin/{directory}"]
        mounts += ["--mount", f"type=bind,src={root / 'fixture' / 'sources'},dst=/fixture,readonly"]
        docker("run", "--pull", "never", "-d", "--name", name, "--network", network, "--cpus", "2",
            "--memory", "1536m", "--memory-swap", "1536m", "--restart", "no",
            "--env-file", str(env), *mounts, args.image)
        ip = json.loads(docker("inspect", name))[0]["NetworkSettings"]["Networks"][network]["IPAddress"]
        base, metrics = f"http://{ip}:8080", f"http://{ip}:8081/actuator/prometheus"
        # All targets are exact disposable internal IPs, never ambient HTTP proxies.
        telemetry = urllib.request.build_opener(urllib.request.ProxyHandler({}))
        opener = urllib.request.build_opener(urllib.request.ProxyHandler({}),
            urllib.request.HTTPCookieProcessor(http.cookiejar.CookieJar()))
        def ready():
            for _ in range(180):
                try:
                    page = opener.open(base + "/setup", timeout=5).read().decode()
                    found = re.search(r'<meta[^>]*name="_csrf"[^>]*content="([^"]+)"', page)
                    if found: return found.group(1)
                except (OSError, ValueError): pass
                time.sleep(1)
            raise RuntimeError("Isolated application startup timeout")
        csrf = ready()
        password = secrets.token_urlsafe(32)
        request("/connect/SetupEndpoint/registerSuperAdmin", {"superAdminRegistration": {
            "username": "fixture-admin", "password": password, "email": "fixture@example.invalid"}})
        login = urllib.parse.urlencode({"username": "fixture-admin", "password": password, "_csrf": csrf}).encode()
        page = opener.open(urllib.request.Request(base + "/login", login), timeout=30).read().decode()
        csrf = re.search(r'<meta[^>]*name="_csrf"[^>]*content="([^"]+)"', page).group(1)
        request("/connect/PluginEndpoint/enablePlugin", {"pluginId": args.metadata_plugin_id})
        request("/connect/PluginEndpoint/enablePlugin", {"pluginId": "org.gameyfin.plugins.download.direct"})
        docker("stop", name)
        docker("run", "--pull", "never", "--rm", "--network", "none", "--user", "0", "--entrypoint", "java",
            "--mount", f"type=bind,src={root / 'db'},dst=/db",
            "--mount", f"type=bind,src={root / 'fixture'},dst=/seed,readonly", args.image,
            "-cp", args.h2_jar, "org.h2.tools.RunScript", "-url", "jdbc:h2:/db/gameyfin_db",
            "-user", "gfadmin", "-password", "gameyfin", "-script", "/seed/seed.sql")
        # These are fixed synthetic database defaults, not real account credentials.
        docker("run", "--pull", "never", "--rm", "--network", "none", "--user", "0", "--entrypoint", "chown",
            "--mount", f"type=bind,src={root / 'db'},dst=/db", args.image,
            "-R", args.runtime_uid + ":" + args.runtime_gid, "/db")
        docker("start", name)
        csrf = ready()
        page = opener.open(urllib.request.Request(base + "/login",
            urllib.parse.urlencode({"username": "fixture-admin", "password": password, "_csrf": csrf}).encode()), timeout=30).read().decode()
        csrf = re.search(r'<meta[^>]*name="_csrf"[^>]*content="([^"]+)"', page).group(1)
        for phase in (("cold", "repeat", "recovery") if args.interrupt_scan else ("cold", "repeat")):
            if phase == "recovery":
                request("/connect/LibraryEndpoint/triggerScan", {"scanType": "FULL", "libraryIds": [27001,27002,27003,27004]})
                active = metric("gameyfin_scans_active")
                if active <= 0: raise RuntimeError("No active scan observed; interruption evidence invalid")
                docker("kill", "--signal", "KILL", name)
                docker("start", name)
                csrf = ready()
                page = opener.open(urllib.request.Request(base + "/login",
                    urllib.parse.urlencode({"username": "fixture-admin", "password": password, "_csrf": csrf}).encode()), timeout=30).read().decode()
                csrf = re.search(r'<meta[^>]*name="_csrf"[^>]*content="([^"]+)"', page).group(1)
                report["interruption"] = {"kind": "forced isolated process interruption", "observedActiveLibraries": active}
            completed, failed = metric("gameyfin_scans_completed_total"), metric("gameyfin_scans_failed_total")
            started, peak_heap, peak_rss = time.monotonic(), 0, 0
            processes = docker("top", name, "-eo", "pid,args").splitlines()[1:]
            java_pids = [int(line.split(None, 1)[0]) for line in processes
                if len(line.split(None, 1)) == 2 and "java" in line.split(None, 1)[1].split()[0]]
            if len(java_pids) != 1: raise RuntimeError("Require one isolated JVM for RSS evidence")
            pid = java_pids[0]
            request("/connect/LibraryEndpoint/triggerScan", {"scanType": "FULL", "libraryIds": [27001,27002,27003,27004]})
            while time.monotonic() - started < 180:
                sample = snapshot()
                peak_heap = max(peak_heap, metric("jvm_memory_used_bytes", 'area="heap"', sample))
                status = Path(f"/proc/{pid}/status").read_text()
                resident = re.search(r"VmRSS:\s+(\d+)", status)
                if not resident: raise RuntimeError("RSS unavailable; do not fabricate peak evidence")
                peak_rss = max(peak_rss, int(resident.group(1)) * 1024)
                done = metric("gameyfin_scans_completed_total", text=sample) - completed
                errors = metric("gameyfin_scans_failed_total", text=sample) - failed
                if done + errors >= 4: break
                time.sleep(0.5)
            else: raise RuntimeError("Scan timed out")
            if errors: raise RuntimeError("Unexpected scan failure")
            games = json.loads(request("/connect/GameEndpoint/getAll", {}))
            if len(games) != 132 or {game["id"] for game in games} != set(expected_games):
                raise RuntimeError("Affected game identity set changed")
            default_count = sum(sum(bool(v["default"]) for v in game["variants"]) for game in games)
            for game in games:
                expected_game = expected_games[game["id"]]
                pinned = [variant for variant in game["variants"] if variant["id"] == expected_game["variantId"]]
                if len(pinned) != 1: raise RuntimeError("Administrator-pinned variant identity changed")
                contents = {content["id"]: content for content in pinned[0]["contents"]}
                if set(contents) != {expected_game["requiredContentId"], expected_game["optionalContentId"]}:
                    raise RuntimeError("Pinned content identities changed")
                required = contents[expected_game["requiredContentId"]]
                optional = contents[expected_game["optionalContentId"]]
                if not required["required"] or required["pathCount"] != 2 or optional["required"] or optional["defaultSelected"]:
                    raise RuntimeError("Grouped/optional content selection semantics changed")
                if args.source_revision != "baseline-unknown":
                    defaults = [variant for variant in game["variants"] if variant["default"]]
                    if len(defaults) != 1 or defaults[0]["id"] != expected_game["variantId"] or not defaults[0]["defaultLocked"]:
                        raise RuntimeError("Candidate did not retain this game's exact pinned default")
            report["scanResults"].append({"phase": phase, "seconds": time.monotonic()-started,
                "completedLibraries": done, "failedLibraries": errors, "sampledPeakHeapBytes": peak_heap,
                "sampledPeakJvmRssBytes": peak_rss,
                "defaultVariants": default_count})
        providers = json.loads(request("/connect/DownloadProviderEndpoint/getProviders", {}))
        if len(providers) != 1: raise RuntimeError("Expected only explicitly supplied direct provider")
        selected_game = manifest["games"][0]
        report["downloads"] = []
        for include_optional in (False, True):
            content_ids = [selected_game["requiredContentId"]]
            members = selected_game["requiredMembers"].copy()
            if include_optional:
                content_ids.append(selected_game["optionalContentId"])
                members += selected_game["optionalMembers"]
            query = urllib.parse.urlencode({"provider": providers[0]["key"],
                "variantId": selected_game["variantId"], "contentIds": ",".join(map(str, content_ids)),
                "explicitSelection": "true"})
            route = "/download/" + str(selected_game["gameId"])
            estimate = int(request(route + "/estimate?" + query))
            response = opener.open(base + route + "?" + query, timeout=30)
            payload = response.read(2 * 1024 * 1024 + 1)
            if len(payload) > 2 * 1024 * 1024: raise RuntimeError("Synthetic archive exceeded bound")
            archive_members = selected_game["requiredArchiveMembers"].copy()
            if include_optional: archive_members.update(selected_game["optionalArchiveMembers"])
            expected = {name: manifest["sha256"][member] for name, member in archive_members.items()}
            with zipfile.ZipFile(io.BytesIO(payload)) as archive:
                entries = [entry for entry in archive.infolist() if not entry.is_dir()]
                if len(entries) != len(expected): raise RuntimeError("Unexpected ZIP entry count")
                if any(entry.file_size > 65536 for entry in entries) or sum(entry.file_size for entry in entries) > 131072:
                    raise RuntimeError("Uncompressed synthetic archive exceeded bound")
                actual_members = {entry.filename: hashlib.sha256(archive.read(entry)).hexdigest() for entry in entries}
                selected_bytes_match = actual_members == expected
                if not selected_bytes_match:
                    raise RuntimeError("Selected ZIP members or bytes changed")
                if estimate != sum(entry.file_size for entry in entries): raise RuntimeError("Estimate disagrees with selected bytes")
            report["downloads"].append({"optionalSelected": include_optional, "estimateBytes": estimate,
                "archiveBytes": len(payload), "memberHashes": actual_members,
                "expectedMemberHashes": expected, "selectedBytesMatch": selected_bytes_match})
        actual = {p.relative_to(root / "fixture" / "sources").as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in (root / "fixture" / "sources").rglob("*") if p.is_file()}
        assert actual == manifest["sha256"], "Synthetic sources changed"
        report["sourceHashesUnchanged"] = True
        if args.external_probe:
            child_env = os.environ.copy()
            child_env.update({"GAMEYFIN_SMOKE_USERNAME": "fixture-admin", "GAMEYFIN_SMOKE_PASSWORD": password,
                "GAMEYFIN_DOCKER_PREFIX": args.docker_prefix})
            hook = subprocess.run(["python3", str(args.external_probe)], input=json.dumps({
                "backend": name, "backendUrl": base, "network": network, "provider": providers[0]["key"],
                "fixtureManifest": manifest, "sourceRevision": args.source_revision, "proxyImage": args.proxy_image}),
                text=True, capture_output=True, env=child_env, timeout=180)
            if hook.returncode:
                error = hook.stderr.replace(password, "[redacted]").splitlines()
                report["externalProbeFailure"] = error[-1] if error else "External probe failed without diagnostic"
                args.output.parent.mkdir(parents=True, exist_ok=True)
                args.output.write_text(json.dumps(report, indent=2) + "\n")
                raise RuntimeError("External isolated probe failed: " + report["externalProbeFailure"])
            report["externalProbe"] = json.loads(hook.stdout)
        final_state = json.loads(docker("inspect", name))[0]
        report["restartCount"] = final_state["RestartCount"]
        report["oomKilled"] = final_state["State"]["OOMKilled"]
        report["health"] = json.loads(telemetry.open(metrics.replace("prometheus", "health"), timeout=10).read())["status"]
        application_log = subprocess.run([*docker_command, "logs", name], text=True, capture_output=True, check=True)
        log_lines = (application_log.stdout + application_log.stderr).splitlines()
        report["errorLogLineCount"] = sum(bool(re.search(r"\bERROR\b", line)) for line in log_lines)
        report["oomErrorLineCount"] = sum("OutOfMemoryError" in line for line in log_lines)
        report["closedDatabaseErrorLineCount"] = sum("database is already closed" in line.lower() or "database has been closed" in line.lower() for line in log_lines)
        if report["oomKilled"] or report["health"] != "UP": raise RuntimeError("Fixture unhealthy after scans")
        report["remainingGaps"] = ["production acceptance"] + ([] if args.interrupt_scan else ["failure/recovery"])
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(report, indent=2) + "\n")
    except Exception as error:
        # Preserve bounded diagnostics before exact cleanup, without log bodies,
        # runtime environment, passwords, tokens or command-line arguments.
        report["failureType"] = type(error).__name__
        state = subprocess.run([*docker_command, "inspect", name], capture_output=True, text=True, timeout=15)
        if state.returncode == 0:
            inspected = json.loads(state.stdout)[0]
            report["failureContainerState"] = {key: inspected["State"].get(key)
                for key in ("Status", "Running", "OOMKilled", "ExitCode")}
            logs = subprocess.run([*docker_command, "logs", "--tail", "200", name], capture_output=True, text=True, timeout=15)
            lines = (logs.stdout + logs.stderr).splitlines()
            report["failureLogCounts"] = {kind: sum(kind in line for line in lines)
                for kind in ("ERROR", "OutOfMemoryError", "SQLException", "HikariPool", "TimeoutException")}
            threads = subprocess.run([*docker_command, "exec", name, "sh", "-c",
                "jcmd $(pgrep -o java) Thread.print"], capture_output=True, text=True, timeout=15)
            report["failureThreadFrames"] = [line.strip() for line in threads.stdout.splitlines()
                if re.match(r"\s+(?:java.lang.Thread.State:|at (?:org.gameyfin\.|org.h2\.|com.zaxxer.hikari\.|io.micrometer\.))", line)][:250]
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(report, indent=2) + "\n")
        raise
    finally:
        subprocess.run([*docker_command, "rm", "-f", name], capture_output=True)
        subprocess.run([*docker_command, "network", "rm", network], capture_output=True)
        container_check = subprocess.run([*docker_command, "ps", "-a", "--filter", "name=^/" + name + "$", "--format", "{{.Names}}"], capture_output=True, text=True)
        network_check = subprocess.run([*docker_command, "network", "ls", "--filter", "name=^" + network + "$", "--format", "{{.Name}}"], capture_output=True, text=True)
        if container_check.returncode or network_check.returncode or container_check.stdout.strip() or network_check.stdout.strip():
            raise RuntimeError("Exact synthetic resource cleanup could not be verified; inspect recorded names")
        # Keep private generated leaf for explicit inspected cleanup; never broad prune.
        print("Private synthetic test leaf (remove after inspection):", root)


if __name__ == "__main__":
    main()
